tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "mas"
brew "cask"
brew "curl"
brew "go"
brew "ruby"
brew "staticcheck"
brew "youtube-dl"
brew "ffmpeg"
brew "pre-commit"
brew "zsh"
brew "zsh-syntax-highlighting"
cask "iterm2"
cask "bitwarden"
cask "font-fira-code"
cask "movist-pro"
cask "visual-studio-code"
cask "microsoft-edge"
cask "docker"
cask "telegram-desktop"
cask "microsoft-excel"
cask "microsoft-powerpoint"
cask "google-drive"
mas "KakaoTalk", id: 869223134
mas "Divvy", id: 413857545
mas "Irvue", id: 1039633667
mas "Microsoft To Do", id:1274495053
mas "Bitwarden", id:1352778147
